# no version needed since 2020

services:
  jekyll:
    image: bretfisher/jekyll-serve
    # Add --incremental to the commandline
    # https://github.com/BretFisher/jekyll-serve/blob/2119a31476e1c6004a4bea4739b9160fc73e7bda/Dockerfile#L27C5-L27C94
    command: [ "bundle", "exec", "jekyll", "serve", "--force_polling", "-H", "0.0.0.0", "-P", "4000", "--incremental" ]
    volumes:
      - .:/site:Z
    ports:
      - '4000:4000'
